// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAccount(arg1) {
  return window['go']['main']['BackgroundController']['AddAccount'](arg1);
}

export function AddAddress(arg1) {
  return window['go']['main']['BackgroundController']['AddAddress'](arg1);
}

export function AddAddresses(arg1) {
  return window['go']['main']['BackgroundController']['AddAddresses'](arg1);
}

export function AddCard(arg1) {
  return window['go']['main']['BackgroundController']['AddCard'](arg1);
}

export function AddCards(arg1) {
  return window['go']['main']['BackgroundController']['AddCards'](arg1);
}

export function AddEmails(arg1) {
  return window['go']['main']['BackgroundController']['AddEmails'](arg1);
}

export function CreateInfoTask(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['BackgroundController']['CreateInfoTask'](arg1, arg2, arg3, arg4, arg5);
}

export function CreatePrimeTask(arg1, arg2, arg3) {
  return window['go']['main']['BackgroundController']['CreatePrimeTask'](arg1, arg2, arg3);
}

export function CreateTask() {
  return window['go']['main']['BackgroundController']['CreateTask']();
}

export function DeleteAccount(arg1) {
  return window['go']['main']['BackgroundController']['DeleteAccount'](arg1);
}

export function DeleteAddress(arg1) {
  return window['go']['main']['BackgroundController']['DeleteAddress'](arg1);
}

export function DeleteCard(arg1) {
  return window['go']['main']['BackgroundController']['DeleteCard'](arg1);
}

export function EditAccount(arg1) {
  return window['go']['main']['BackgroundController']['EditAccount'](arg1);
}

export function EditAddress(arg1) {
  return window['go']['main']['BackgroundController']['EditAddress'](arg1);
}

export function EditCard(arg1) {
  return window['go']['main']['BackgroundController']['EditCard'](arg1);
}

export function EditEmails(arg1) {
  return window['go']['main']['BackgroundController']['EditEmails'](arg1);
}

export function EditProxies(arg1) {
  return window['go']['main']['BackgroundController']['EditProxies'](arg1);
}

export function GenerateHMELoop() {
  return window['go']['main']['BackgroundController']['GenerateHMELoop']();
}

export function IcloudLogin(arg1, arg2) {
  return window['go']['main']['BackgroundController']['IcloudLogin'](arg1, arg2);
}

export function ImapLogin(arg1, arg2) {
  return window['go']['main']['BackgroundController']['ImapLogin'](arg1, arg2);
}

export function JigAddress(arg1) {
  return window['go']['main']['BackgroundController']['JigAddress'](arg1);
}

export function LoadAccounts() {
  return window['go']['main']['BackgroundController']['LoadAccounts']();
}

export function LoadAddresses() {
  return window['go']['main']['BackgroundController']['LoadAddresses']();
}

export function LoadCards() {
  return window['go']['main']['BackgroundController']['LoadCards']();
}

export function LoadEmails() {
  return window['go']['main']['BackgroundController']['LoadEmails']();
}

export function LoadProxies() {
  return window['go']['main']['BackgroundController']['LoadProxies']();
}

export function SaveAccounts(arg1) {
  return window['go']['main']['BackgroundController']['SaveAccounts'](arg1);
}

export function SaveAddresses(arg1) {
  return window['go']['main']['BackgroundController']['SaveAddresses'](arg1);
}

export function SaveCards(arg1) {
  return window['go']['main']['BackgroundController']['SaveCards'](arg1);
}

export function SaveData(arg1, arg2) {
  return window['go']['main']['BackgroundController']['SaveData'](arg1, arg2);
}

export function SaveEmails(arg1) {
  return window['go']['main']['BackgroundController']['SaveEmails'](arg1);
}

export function SaveProxies(arg1) {
  return window['go']['main']['BackgroundController']['SaveProxies'](arg1);
}

export function StopAccTask(arg1) {
  return window['go']['main']['BackgroundController']['StopAccTask'](arg1);
}

export function StopTask(arg1) {
  return window['go']['main']['BackgroundController']['StopTask'](arg1);
}

export function SubmitOTP(arg1) {
  return window['go']['main']['BackgroundController']['SubmitOTP'](arg1);
}

export function TestSms(arg1, arg2, arg3) {
  return window['go']['main']['BackgroundController']['TestSms'](arg1, arg2, arg3);
}
