// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddAccount(arg1:main.Account):Promise<void>;

export function AddAddress(arg1:main.Address):Promise<void>;

export function AddAddresses(arg1:Array<main.Address>):Promise<void>;

export function AddCard(arg1:main.Card):Promise<void>;

export function AddCards(arg1:Array<main.Card>):Promise<void>;

export function AddEmails(arg1:string):Promise<void>;

export function CreateInfoTask(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function CreatePrimeTask(arg1:string,arg2:string,arg3:string):Promise<void>;

export function CreateTask():Promise<void>;

export function DeleteAccount(arg1:main.Account):Promise<void>;

export function DeleteAddress(arg1:main.Address):Promise<void>;

export function DeleteCard(arg1:main.Card):Promise<void>;

export function EditAccount(arg1:main.Account):Promise<void>;

export function EditAddress(arg1:main.Address):Promise<void>;

export function EditCard(arg1:main.Card):Promise<void>;

export function EditEmails(arg1:string):Promise<void>;

export function EditProxies(arg1:string):Promise<void>;

export function GenerateHMELoop():Promise<void>;

export function IcloudLogin(arg1:string,arg2:string):Promise<void>;

export function ImapLogin(arg1:string,arg2:string):Promise<void>;

export function JigAddress(arg1:string):Promise<string>;

export function LoadAccounts():Promise<void>;

export function LoadAddresses():Promise<void>;

export function LoadCards():Promise<void>;

export function LoadEmails():Promise<void>;

export function LoadProxies():Promise<void>;

export function SaveAccounts(arg1:Array<main.Account>):Promise<void>;

export function SaveAddresses(arg1:Array<main.Address>):Promise<void>;

export function SaveCards(arg1:Array<main.Card>):Promise<void>;

export function SaveData(arg1:string,arg2:string):Promise<void>;

export function SaveEmails(arg1:string):Promise<void>;

export function SaveProxies(arg1:string):Promise<void>;

export function StopAccTask(arg1:string):Promise<void>;

export function StopTask(arg1:string):Promise<void>;

export function SubmitOTP(arg1:string):Promise<void>;

export function TestSms(arg1:string,arg2:string,arg3:string):Promise<void>;
