// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function LoadSettings():Promise<void>;

export function SaveSettings(arg1:main.Settings,arg2:boolean):Promise<void>;
