// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadSettings() {
  return window['go']['main']['SettingsController']['LoadSettings']();
}

export function SaveSettings(arg1, arg2) {
  return window['go']['main']['SettingsController']['SaveSettings'](arg1, arg2);
}
